import { Inter } from "next/font/google";
import "./globals.css";
import LiffProvider from "@/components/LIFF/LiffProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LINE LIFF",
  description: "Generated by create next app",
};

export default  function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        
        <LiffProvider>
        {children}
        </LiffProvider>

      </body>
    </html>
  );
}
